### ISSUE TITLE
Does not work correctly

### ISSUE THREAD

**Issue by David-Valters** [SixArm/checkline#1]
When running the command from the example:

`cat example.txt | checkline`
this is the result:
![зображення](https://github.com/SixArm/checkline/assets/46930139/53cfd887-81f9-4d42-8792-834dc75508ff)
if check, the next result will be:
![зображення](https://github.com/SixArm/checkline/assets/46930139/f4641f55-e48b-47c3-8596-8071bd1c0e4d)
file contents:
![зображення](https://github.com/SixArm/checkline/assets/46930139/15742e4e-5fac-4b85-bfb7-54c03e920612)

The program was launched in the alacritty and konsole(kde) terminals.
Shell: zsh and bash

But everything works correctly in the Visual Studio Code terminal
![зображення](https://github.com/SixArm/checkline/assets/46930139/f5a5cf51-2572-4e00-9802-331f49dc73b4)

OS: Arch Linux x86_64
DE: Plasma 6.0.4

**Comment by joelparkerhenderson** [comment]
Thank you for reporting this. I confirm this bug happens now with Alacritty on macOS. I'm also seeing various posts about issues with Alacritty, Cursive (which is the Rust crate that provides terminal user interface), fonts, and locales. I'll take a look.

**Comment by joelparkerhenderson** [comment]
I fixed the colors, and it now works on Alacritty on macOS. 

Can you try updating, and see if the new version 1.1.3 works for you?

**Comment by David-Valters** [comment]
> Can you try updating, and see if the new version 1.1.3 works for you?

It works, thanks!
![зображення](https://github.com/SixArm/checkline/assets/46930139/cb923f1a-2972-49ac-bc88-20752df84500)

**Comment by joelparkerhenderson** [comment]
Good, thank you again for reporting this bug-- this code improvement is because of you! <3
